{
 "title": "Mini Stake Pool - Advanced Dashboard (Mainnet)",
 "description": "Mini Pool Grafana Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forged_int{alias=\"bp_main\"} / cardano_node_metrics_Forge_node_is_leader_int{alias=\"bp_main\"} * 100)",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "BP Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{instance=\"192.168.1.116:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.1.116:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.1.116:9100\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.1.116:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.1.116:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "BP Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"bp_main\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk BP",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.1.116:9100\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "jaws_relay"
    }
   ]
  },
  {
   "title": "RAM BP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"192.168.1.116:9100\"})",
     "legendFormat": "Total Ram"
    }
   ]
  },
  {
   "title": "BP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=\"192.168.1.116:9100\"})"
    }
   ]
  },
  {
   "title": "BP TX's processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"bp_main\"}",
     "legendFormat": "JAWS_Core"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"bp_main\"} - cardano_node_metrics_Forge_node_not_leader_int{alias=\"bp_main\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"bp_main\"}"
    }
   ]
  },
  {
   "title": "Relay Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{instance=\"192.168.1.112:9100\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.1.112:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.1.112:9100\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.1.112:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.1.112:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int{alias=\"bp_main\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Epoch Completion [%]",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"bp_main\"}/432000*100"
    }
   ]
  },
  {
   "title": "Relay Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{alias=\"relay_main\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk Relay",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.1.112:9100\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "jaws_relay"
    }
   ]
  },
  {
   "title": "RAM Relay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"192.168.1.112:9100\"})",
     "legendFormat": "Total Ram"
    }
   ]
  },
  {
   "title": "Relay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=\"192.168.1.112:9100\"})"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{alias=\"bp_main\"} * 100",
     "legendFormat": "BP"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relay_main\"} * 100",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"bp_main\"}",
     "legendFormat": "BP"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relay_main\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Slot height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"bp_main\"}",
     "legendFormat": "BP"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay_main\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"bp_main\"}/(1024*1024)",
     "legendFormat": "BP"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay_main\"}/(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"bp_main\"}/(1024*1024)",
     "legendFormat": "BP"
    },
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay_main\"}/(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Nodes peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"bp_main\"}",
     "legendFormat": "BP"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay_main\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Memory Utilization Relay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.1.112:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.1.112:9100\"})))* 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Utilization BP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.1.116:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.1.116:9100\"})))* 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"docker0\"}[1h]) * 3600",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"192.168.1.112:9100\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"192.168.1.112:9100\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"192.168.1.112:9100\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "BP Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"192.168.1.116:9100\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"192.168.1.116:9100\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"192.168.1.116:9100\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "BP Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"bp_main\"}",
     "legendFormat": "BP"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"bp_main\"}[150s]) *60",
     "legendFormat": "BP"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relay_main\"}[150s]) *60",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Time Synchronization BP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=\"192.168.1.116:9100\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{instance=\"192.168.1.116:9100\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=\"192.168.1.116:9100\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization Relay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=\"192.168.1.112:9100\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{instance=\"192.168.1.112:9100\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=\"192.168.1.112:9100\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{alias}}" }
   ]
  }
 ]
}